[[SuperLU_DIST]]
arch = "aarch64"
git-tree-sha1 = "4dc992b95c0e776ecbbf183962219b2bd15979c7"
mpi = "mpich"
os = "macos"

    [[SuperLU_DIST.download]]
    sha256 = "9e4710629880795149347fa9bc8c62d862f8feb535b024579d2f78124fd4c25e"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[SuperLU_DIST]]
arch = "aarch64"
git-tree-sha1 = "7ea8b00036bd803e39ee59eb2f3854629a984cd5"
mpi = "mpitrampoline"
os = "macos"

    [[SuperLU_DIST.download]]
    sha256 = "2567ba497261eaa439119362d73df4c93239ba59faf930d6133d5253e41ebc52"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[SuperLU_DIST]]
arch = "aarch64"
git-tree-sha1 = "22af9c5214e14198929d505b0a3cfbd22da479c4"
mpi = "openmpi"
os = "macos"

    [[SuperLU_DIST.download]]
    sha256 = "5257af8dd95fd2574498b924cade58f989578f66b8347b96f534df1de0d67037"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.aarch64-apple-darwin-mpi+openmpi.tar.gz"
[[SuperLU_DIST]]
arch = "aarch64"
git-tree-sha1 = "f43d933d86335152b5cd61f5015a40423a07e292"
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "381d6b5342823144cb9256928f15120528220e514ffa61841f220100e0839dd6"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.aarch64-linux-gnu-mpi+mpich.tar.gz"
[[SuperLU_DIST]]
arch = "aarch64"
git-tree-sha1 = "673affa93489648aa134ca353a04f6946212d189"
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "c3a7b89a21a3bc9d63c63dbaf0b3435293f81322061a5989a9fe0aa9d6927aa8"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.aarch64-linux-gnu-mpi+mpitrampoline.tar.gz"
[[SuperLU_DIST]]
arch = "aarch64"
git-tree-sha1 = "13da9bfa887d354e4f67f2966cb36a10de053986"
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "9059fff357e88630af5a6a502d2f4bb5073fd6f5e5cfc3de1499a49097d9a4b3"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.aarch64-linux-gnu-mpi+openmpi.tar.gz"
[[SuperLU_DIST]]
arch = "aarch64"
git-tree-sha1 = "72e0f1574adb7a094d452dcab7a9fd296a1efd45"
libc = "musl"
mpi = "mpich"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "d26f7dbdc7ed59ad676da2a4bf1819a711512585cfaf2f1e519dcaf2755dfdd9"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.aarch64-linux-musl-mpi+mpich.tar.gz"
[[SuperLU_DIST]]
arch = "aarch64"
git-tree-sha1 = "ebd87121288c599a53245ff3df8f02dde0f97f74"
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "8c3218992590757edd250a0358b63f99e9f82d0ee47e468594a3fd1b6508c540"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.aarch64-linux-musl-mpi+openmpi.tar.gz"
[[SuperLU_DIST]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b06dbe0f8b6b9dc6104aa51e4a4eaf4a9196eb41"
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "5ad45724719cef5ce412e164c9ccab6edb382a6de4731941adc34f5b8849ac03"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.armv6l-linux-gnueabihf-mpi+mpich.tar.gz"
[[SuperLU_DIST]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ab1b97f62d53570939052323cbdef7993b7d40cc"
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "db74dc141e19a0a512303659a847ec0bf7f70067a9c0a6e4a054cd42d9d57909"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.armv6l-linux-gnueabihf-mpi+mpitrampoline.tar.gz"
[[SuperLU_DIST]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8ba1f15526bd9c3536836cdf8041c2fcdba0ce84"
libc = "musl"
mpi = "mpich"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "e43f26a1fa1e015af520d7675fa1af6dce9c870c3512841eaf56f2f693d613b3"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.armv6l-linux-musleabihf-mpi+mpich.tar.gz"
[[SuperLU_DIST]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9c79f409237b4e97d418c654e01a532a164811a8"
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "3fd6e122e13476da686a09c36672058d873da41a720fa8f76bc6721ed8fc341f"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.armv6l-linux-musleabihf-mpi+openmpi.tar.gz"
[[SuperLU_DIST]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "942b51e1224941107cb814e45ab573b7b881a541"
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "1ac671086d8e7446a5b580737d48e10eca63c6e67dcff5b94b8f0aadb14fc51f"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.armv7l-linux-gnueabihf-mpi+mpich.tar.gz"
[[SuperLU_DIST]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ccd3cd9fcab36c0c22864d5dae460a9ad0bb34f8"
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "7e9395882938241ddd27df8bbab642872134b10e703c98cdcdc73ffcc759134a"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.armv7l-linux-gnueabihf-mpi+mpitrampoline.tar.gz"
[[SuperLU_DIST]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0ec38fd57c72a1eb5ea9fd06ecc59fbd4e44c334"
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "d0058e57a15e4013877292b560d63d3d09d511d0eb897f5448a2b28879582bdd"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.armv7l-linux-gnueabihf-mpi+openmpi.tar.gz"
[[SuperLU_DIST]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9993aa2204e918eaae7f7e1827e5cda814e495d2"
libc = "musl"
mpi = "mpich"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "13abfe890cf08211b720b59d081247cb66ed10fc2920e26c9a40b67ff71f76aa"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.armv7l-linux-musleabihf-mpi+mpich.tar.gz"
[[SuperLU_DIST]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0fc50ad60efdf2bfab756f2dfc10fc0007ee1415"
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "ffcdef98e595564ac5b1a57fdd0204e3c60662b2c4308ab6a9299e34a70d0a58"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.armv7l-linux-musleabihf-mpi+openmpi.tar.gz"
[[SuperLU_DIST]]
arch = "i686"
git-tree-sha1 = "a0cdd960e128f862ab6491a96c6b3928ea31d5e6"
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "4284cb9faac995548efef74fc0e08d97ed8e3e1a10b0ad115a891f9a99c20532"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.i686-linux-gnu-mpi+mpich.tar.gz"
[[SuperLU_DIST]]
arch = "i686"
git-tree-sha1 = "2232201d2580655673622217efb9bff476d4e29a"
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "b74b989aa99e3b930a0c52a5f4a83082d31ac0fff8ea4d9d1ce333b35b934499"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.i686-linux-gnu-mpi+mpitrampoline.tar.gz"
[[SuperLU_DIST]]
arch = "i686"
git-tree-sha1 = "7095e3c392e3950d5a9783adee8d43125e459ed3"
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "45d107ea7e3161b2b49b0a644d1046b5e614fd4c78272e76d3dd72a44ba79a07"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.i686-linux-gnu-mpi+openmpi.tar.gz"
[[SuperLU_DIST]]
arch = "i686"
git-tree-sha1 = "e9bb5e6a15804ce8a3f2c877fbd7173101c3b616"
libc = "musl"
mpi = "mpich"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "26362f7cbca47723dbcdc3bac54dc9e9db837bc8cdbbd0ca93bb2eb0ab5f9b19"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.i686-linux-musl-mpi+mpich.tar.gz"
[[SuperLU_DIST]]
arch = "i686"
git-tree-sha1 = "dba61669bc5ab694e46e9913d90f8be37f8b2acb"
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "8cba564a3a3b152647c382bcd70eec801bb0376580881d2f70c9fc16a9abfcf8"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.i686-linux-musl-mpi+openmpi.tar.gz"
[[SuperLU_DIST]]
arch = "i686"
git-tree-sha1 = "9e2ec607f9c8664e6b94a32ba03a7e88c37dc316"
mpi = "microsoftmpi"
os = "windows"

    [[SuperLU_DIST.download]]
    sha256 = "e4a4992f1fae0d519f10b281b731e76b4d9389f2593dca5e70d75ccc498f728f"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.i686-w64-mingw32-mpi+microsoftmpi.tar.gz"
[[SuperLU_DIST]]
arch = "powerpc64le"
git-tree-sha1 = "9bb6bf8ee6879993b6431497864c5ef506414797"
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "797fc9da0094977975e22259d432228cce02c253e7efe5daf9c8e2d5ed2c57d2"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.powerpc64le-linux-gnu-mpi+mpich.tar.gz"
[[SuperLU_DIST]]
arch = "powerpc64le"
git-tree-sha1 = "2e4031bcff92b52595e509fa049f7e56e66769cc"
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "b6c13761559d4a76f4f19408c270aaab1b7be3ff83ac655f6104b2a451ece98b"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.powerpc64le-linux-gnu-mpi+mpitrampoline.tar.gz"
[[SuperLU_DIST]]
arch = "powerpc64le"
git-tree-sha1 = "fd4b30261bb72f146c1d7db5fee1dc81ce122be8"
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "bab866beab2c043abb091c6a67d95a18ebd4f93550ef5f9d3d0467880bc43984"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.powerpc64le-linux-gnu-mpi+openmpi.tar.gz"
[[SuperLU_DIST]]
arch = "x86_64"
git-tree-sha1 = "5ee266c77972e985adc3ed40e62e00a3e058ab5a"
mpi = "mpich"
os = "macos"

    [[SuperLU_DIST.download]]
    sha256 = "2d11dc01fa1617532fb94e7b19cffa18b00e873650527aa728815fdf394185b8"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[SuperLU_DIST]]
arch = "x86_64"
git-tree-sha1 = "303e776dd3a71e1249eba8c34133731a539c09fa"
mpi = "mpitrampoline"
os = "macos"

    [[SuperLU_DIST.download]]
    sha256 = "8919118287d7c5f4328afcc5f49229eed6f8129a2f82165cbe6e032d0ea27c0e"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[SuperLU_DIST]]
arch = "x86_64"
git-tree-sha1 = "1cf6e06b3a1e53955bdf5bc98cda880576c2c61e"
mpi = "openmpi"
os = "macos"

    [[SuperLU_DIST.download]]
    sha256 = "3e7122a3a0f6138691828624fac37beb8d9ee1ab26b5a9c0c02e2420bb7c1ca7"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[SuperLU_DIST]]
arch = "x86_64"
git-tree-sha1 = "9c535f313f10a5cbe213d4135181424781e9111d"
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "58a89bb0b72f67f171ad9f3634e28eeb3107ac5c22541c7f75e1355fff17b553"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.x86_64-linux-gnu-mpi+mpich.tar.gz"
[[SuperLU_DIST]]
arch = "x86_64"
git-tree-sha1 = "52efb407faaf005062198fd1c14cfeeb9b3603db"
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "b1f9a540a530c91a28ad51c7b31b4ca0c33000d229fa5c6b0592c8349f716867"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.x86_64-linux-gnu-mpi+mpitrampoline.tar.gz"
[[SuperLU_DIST]]
arch = "x86_64"
git-tree-sha1 = "d6fb318e81e9aaf61a570f68382e97004234e27f"
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "15e005357169e3e465114239e9e7d10e3ddf89384e279924d7c1e0284b307b9f"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.x86_64-linux-gnu-mpi+openmpi.tar.gz"
[[SuperLU_DIST]]
arch = "x86_64"
git-tree-sha1 = "936fc025f27bbc82a0a86be54cc6c7eafeafd80a"
libc = "musl"
mpi = "mpich"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "a0721ef22a09d3f673b03dc6fa6a1734ab9ddfffc231342d29b224f4b15c8d0b"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.x86_64-linux-musl-mpi+mpich.tar.gz"
[[SuperLU_DIST]]
arch = "x86_64"
git-tree-sha1 = "9f1849d3852f5d2ceaaf643aea2f491237746802"
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "0ced1c0ec99ef18ff0d8bb3b16a194442beb02c522e27c0585ef85e7cc8cdc27"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.x86_64-linux-musl-mpi+openmpi.tar.gz"
[[SuperLU_DIST]]
arch = "x86_64"
git-tree-sha1 = "89d5aad9f12993994984889ab1caf3db2442c83e"
mpi = "mpich"
os = "freebsd"

    [[SuperLU_DIST.download]]
    sha256 = "466eb2b7dfe7ea999c2342f16e5732591836ef32a5342712e480827a0450aee8"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.x86_64-unknown-freebsd-mpi+mpich.tar.gz"
[[SuperLU_DIST]]
arch = "x86_64"
git-tree-sha1 = "ed303bd041cde4547f1a819d0f8ff2c51a96abd1"
mpi = "microsoftmpi"
os = "windows"

    [[SuperLU_DIST.download]]
    sha256 = "199760307138f7596130d457f2bf331dfde8a20f8d63280153ae6e64fc45e78a"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.2.1+0/SuperLU_DIST.v8.2.1.x86_64-w64-mingw32-mpi+microsoftmpi.tar.gz"
