[[SuperLU_DIST]]
arch = "aarch64"
git-tree-sha1 = "931201dc062b7876e69ece7f7666190355e36442"
lazy = true
mpi = "mpich"
os = "macos"

    [[SuperLU_DIST.download]]
    sha256 = "218fff186130746beb9d79358de77ae5271e8fa27b33a6fe11f538811fbd7dcb"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[SuperLU_DIST]]
arch = "aarch64"
git-tree-sha1 = "6146a3320e5d1f3f2797c9e0df3db23226cdc1cb"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[SuperLU_DIST.download]]
    sha256 = "4703c75568892efb55745f698afab1d42729d1adf1395d6819c253a154330834"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[SuperLU_DIST]]
arch = "aarch64"
git-tree-sha1 = "52885703b1f7e6aaeb6551d2e095068b386e0438"
lazy = true
mpi = "openmpi"
os = "macos"

    [[SuperLU_DIST.download]]
    sha256 = "0a0a294a2320670327b4bc72c1b3a35c50470517dee6b9a727b25ce8a10483fb"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.aarch64-apple-darwin-mpi+openmpi.tar.gz"
[[SuperLU_DIST]]
arch = "aarch64"
git-tree-sha1 = "a1c09b862b0eefd7a0864ee4db6fc3846ca7441b"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "9344918410d6e5ec2c94b2f57a22eb8c1a58b96c952e796ad7423efca564c3bc"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.aarch64-linux-gnu-mpi+mpich.tar.gz"
[[SuperLU_DIST]]
arch = "aarch64"
git-tree-sha1 = "b655717e4d4cc4593f7bde3749c883c6ab2a2b58"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "6bc71ff015eea04b689caf8f0f8947df6b1d3b987962dbee0fa4a14b095519cb"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.aarch64-linux-gnu-mpi+mpitrampoline.tar.gz"
[[SuperLU_DIST]]
arch = "aarch64"
git-tree-sha1 = "e04ea3092d589fea21e779d3ccd754f3b9366793"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "7047aa3178370f87ef754af8d27fd5485d95e375e90bb341e23cbc94f2c9d940"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.aarch64-linux-gnu-mpi+openmpi.tar.gz"
[[SuperLU_DIST]]
arch = "aarch64"
git-tree-sha1 = "97644b674730341a7a38d8116cbb5f9276b7db13"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "9c9913439ccd43d1b9019e5efccf0906de5c5717bc2a0375ddeafd583e8b2b3f"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.aarch64-linux-musl-mpi+mpich.tar.gz"
[[SuperLU_DIST]]
arch = "aarch64"
git-tree-sha1 = "148f68583efbf359ceadcf624c1957b5f78a27d7"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "d32dd88a17082008a118e33d3f762cd64ff4ca9661f848fd2762408e8f833b4a"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.aarch64-linux-musl-mpi+openmpi.tar.gz"
[[SuperLU_DIST]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d94e53c1072e962c1453e846ae317a33cb34ed09"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "e793671dcaee63c37d7335243f6b6e36195fd99c40647c471859296c10f2880c"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.armv6l-linux-gnueabihf-mpi+mpich.tar.gz"
[[SuperLU_DIST]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4ba7fce88667a48f45ecef1ea25032036e281cf5"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "676d6a6915dbdd8bd5815654306576e28425f0eefd3f9f77ebd96e1760a98607"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.armv6l-linux-gnueabihf-mpi+mpitrampoline.tar.gz"
[[SuperLU_DIST]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cbedcc3e87fdd3bf6d2c4d0fd8175af024574ba3"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "9caba07d88fdfce23beb5c3d4422f35821c616fd2d8ffff5c5a8246cf33292e9"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.armv6l-linux-musleabihf-mpi+mpich.tar.gz"
[[SuperLU_DIST]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a4840d3622f27c52c44d7b520da5a2414c2ccf10"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "a3b46e1ead4c41d39d3ecf18cc957fe962cc4e3124189eeff2a4f680cb6dc544"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.armv6l-linux-musleabihf-mpi+openmpi.tar.gz"
[[SuperLU_DIST]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "63d0a891e3694f694cac4c2c073357af021d6226"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "c3b39412919b61b18776d93f84e7c3421d3a9292436dcd89fe1e71549ac111a3"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.armv7l-linux-gnueabihf-mpi+mpich.tar.gz"
[[SuperLU_DIST]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c463e31d6cde746af1f3401925e360ca991d9c9e"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "88014866fd6ea6e57d37893a174b1e3091dbb3b063c067693020c1475553fae8"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.armv7l-linux-gnueabihf-mpi+mpitrampoline.tar.gz"
[[SuperLU_DIST]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "205e2c442e66bd60c293cbecf5763e032dce11f3"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "e6b0fbe0575b1d46ac8c3e47fe37399a3983462907509ea4ef9f9a729f1a0754"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.armv7l-linux-gnueabihf-mpi+openmpi.tar.gz"
[[SuperLU_DIST]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e7a6e510c663da345fbbb8aa48fc158858ff693b"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "d666b620f2c0a5ca54678c582353722efb302309ce35af81646bfd47c4c4598a"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.armv7l-linux-musleabihf-mpi+mpich.tar.gz"
[[SuperLU_DIST]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c0e010ff7015650536c121290a1b7114eb44185f"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "8c15b0c4401312c1aa33ad6a4395997ca9392caf1909e6326b848f9a003f051d"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.armv7l-linux-musleabihf-mpi+openmpi.tar.gz"
[[SuperLU_DIST]]
arch = "i686"
git-tree-sha1 = "6d1c6e94395c6fdc7d02b4f9a949fbb62e9c11cd"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "f6a2007407085a41ce57c66e06a5783395dca39b89e91ef8b37678bc07439337"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.i686-linux-gnu-mpi+mpich.tar.gz"
[[SuperLU_DIST]]
arch = "i686"
git-tree-sha1 = "467f57dd5a7421944e13637c4c23144e654f1864"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "996ac7f67374b21b688737a296a7d1da1cafed6c299bb2eab1732e265d9b0ffb"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.i686-linux-gnu-mpi+mpitrampoline.tar.gz"
[[SuperLU_DIST]]
arch = "i686"
git-tree-sha1 = "755f344f66fb86fa782a962ccb86b22eb778f0f9"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "e4060c69a2b2b27a826c1225cdfcd6fb6ed7f82b1aa663fda4ced6495eaaf2b6"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.i686-linux-gnu-mpi+openmpi.tar.gz"
[[SuperLU_DIST]]
arch = "i686"
git-tree-sha1 = "02b194b40b1adbc75011f5e984a758ca05362078"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "34f6a680166078f68a237cadc3da5a2fe799f0f185ac1f7b99fcef518eca3993"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.i686-linux-musl-mpi+mpich.tar.gz"
[[SuperLU_DIST]]
arch = "i686"
git-tree-sha1 = "f9aefc6c56907481baf587a33b21ee2e03c3da9a"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "ee783dbd9fae74a4a812f3edf7baeef2596c3fff823bd2d44337d403a9b05952"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.i686-linux-musl-mpi+openmpi.tar.gz"
[[SuperLU_DIST]]
arch = "i686"
git-tree-sha1 = "6774a67f97a3fd0c41f8ce7619571161aa5f7935"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[SuperLU_DIST.download]]
    sha256 = "93146e0b880a9a9f16ee03e8b888eda01b61a4032ee25a2192f00c8c7a8b2652"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.i686-w64-mingw32-mpi+microsoftmpi.tar.gz"
[[SuperLU_DIST]]
arch = "powerpc64le"
git-tree-sha1 = "d826de81e23b38559c69dec9c4b24f0525fe7893"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "62fead396a54debdd8a4264664a6c67d9c713459e2087fe87a3f2c1583a8556a"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.powerpc64le-linux-gnu-mpi+mpich.tar.gz"
[[SuperLU_DIST]]
arch = "powerpc64le"
git-tree-sha1 = "9f968eb2945e27edf3373376fd1d31a089a6c42a"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "e39cff1ab6ecfa08c6bc219d44a95b33dd4026d16daea191ab9bd5a2145352b7"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.powerpc64le-linux-gnu-mpi+mpitrampoline.tar.gz"
[[SuperLU_DIST]]
arch = "powerpc64le"
git-tree-sha1 = "8a11a250c18013289747d8def3cc4cb7e8b8853f"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "696fc8d38ea69259afcc545524465b57d290d6bff82ca6265ab9199d2b404e0d"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.powerpc64le-linux-gnu-mpi+openmpi.tar.gz"
[[SuperLU_DIST]]
arch = "x86_64"
git-tree-sha1 = "8ca7d83405ce3bb98c4a8ab083e758792e1d143a"
lazy = true
mpi = "mpich"
os = "macos"

    [[SuperLU_DIST.download]]
    sha256 = "400acf1229512e4d8167b55b1cd7bdc96ee36ac67409c9e70dc46f2de196dcef"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[SuperLU_DIST]]
arch = "x86_64"
git-tree-sha1 = "81d26272a364ad824ce2804fa2118b317ee43594"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[SuperLU_DIST.download]]
    sha256 = "abcbd2302f88c5cfcfba172129e5beebd7deb6244e88e0f7412e7c071556b73b"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[SuperLU_DIST]]
arch = "x86_64"
git-tree-sha1 = "95920d5b5cf448937afe12d096a2a9c28e3b8ad2"
lazy = true
mpi = "openmpi"
os = "macos"

    [[SuperLU_DIST.download]]
    sha256 = "3d99bcef90e4b7e0aa649ed8f90e1f6b0fc6e68284fc64b68abe74257a23795e"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[SuperLU_DIST]]
arch = "x86_64"
git-tree-sha1 = "0eacf276fedf0f776b824f7e895e00f7c4cca7a7"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "bfde413b0927adba5d9797ca8132b2d1ea69116c495f3c86c0a6729dde647f04"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.x86_64-linux-gnu-mpi+mpich.tar.gz"
[[SuperLU_DIST]]
arch = "x86_64"
git-tree-sha1 = "f1d709c50c889a73cbf924adc1905fa766896e7d"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "ded38b530271810723047801962a087ec5e3d4d8497d0808441ce90f6edeaccb"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.x86_64-linux-gnu-mpi+mpitrampoline.tar.gz"
[[SuperLU_DIST]]
arch = "x86_64"
git-tree-sha1 = "8b5228474b5d2c1106e116b0dba22d9e1c06957f"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "fab3c622830ce224eaf8f420e3bb4087c86f078cbe654cf580eb062956f29016"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.x86_64-linux-gnu-mpi+openmpi.tar.gz"
[[SuperLU_DIST]]
arch = "x86_64"
git-tree-sha1 = "300e1b979dc740df28115d6a168d268e161840ef"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "e8a98030eec2d97867cf9ab63eea050ef2914cc7bfc3f5edea45ee8572ab1cfc"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.x86_64-linux-musl-mpi+mpich.tar.gz"
[[SuperLU_DIST]]
arch = "x86_64"
git-tree-sha1 = "10eea2b4e6578453e19411df8003d50b7a173de4"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[SuperLU_DIST.download]]
    sha256 = "cf45bdf86d16081640c86fa2f0e23534ed09b9e15bf4fc5f469b26c7b06e489a"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.x86_64-linux-musl-mpi+openmpi.tar.gz"
[[SuperLU_DIST]]
arch = "x86_64"
git-tree-sha1 = "0e89861dd46d16b8f34b84e55d72f2f85e2f52d2"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[SuperLU_DIST.download]]
    sha256 = "8cccd277e95233c1022959aaf8f6cb94bb2a0ad821491fe11c008fc670a3af9f"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.x86_64-unknown-freebsd-mpi+mpich.tar.gz"
[[SuperLU_DIST]]
arch = "x86_64"
git-tree-sha1 = "e8f42e4314e553dbe6375b6ac8282852a8834d31"
lazy = true
mpi = "openmpi"
os = "freebsd"

    [[SuperLU_DIST.download]]
    sha256 = "6f07b20530680c4dbdfb22ec68a69fdda6eecd6f0e0a20f47028574b2dc4aa48"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.x86_64-unknown-freebsd-mpi+openmpi.tar.gz"
[[SuperLU_DIST]]
arch = "x86_64"
git-tree-sha1 = "42da9669690f02b1b305c4545f83ff0578c666d4"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[SuperLU_DIST.download]]
    sha256 = "180a883f6c30585acbb2b71af67068160e34f7fc9f04ac94011278df44e3329d"
    url = "https://github.com/JuliaBinaryWrappers/SuperLU_DIST_jll.jl/releases/download/SuperLU_DIST-v8.1.2+0/SuperLU_DIST.v8.1.2.x86_64-w64-mingw32-mpi+microsoftmpi.tar.gz"
