# Autogenerated wrapper script for SuperLU_DIST_jll for x86_64-w64-mingw32
export libsuperlu_dist_Int32, libsuperlu_dist_Int64

using OpenBLAS32_jll
using MicrosoftMPI_jll
using METIS_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("SuperLU_DIST")
JLLWrappers.@declare_library_product(libsuperlu_dist_Int32, "libsuperlu_dist_Int32.dll")
JLLWrappers.@declare_library_product(libsuperlu_dist_Int64, "libsuperlu_dist_Int64.dll")
function __init__()
    JLLWrappers.@generate_init_header(OpenBLAS32_jll, MicrosoftMPI_jll, METIS_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libsuperlu_dist_Int32,
        "bin\\superlu_dist\\Int32\\bin\\libsuperlu_dist_Int32.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsuperlu_dist_Int64,
        "bin\\superlu_dist\\Int64\\bin\\libsuperlu_dist_Int64.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
